#!/bin/env bash


# Replace a specific template in a file.
# $1 file, $2 string to replace, $3 value to insert
replaceTemplate() {
    TEMPLATE_TO_LOOK_FOR="{{[ ]*$2[ ]*}}"
    grep -q -E "$TEMPLATE_TO_LOOK_FOR" $1
    is_in_file=$?
    if [[ is_in_file -eq 1 ]]; then
        echo "Pattern '{{ $2 }}' not found in $1, exiting..." >&2
        exit 1
    fi
    sed -i.bak "s/$TEMPLATE_TO_LOOK_FOR/$3/" $1
}

test() {
    replaceTemplate ./test.txt test try
    cat ./test.txt
}
